[package]
name = "rule"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0", features = ["blocking", "json"] }
regex = "1"
serde_json = "*"
anyhow = "1"
once_cell = "1"
scraper = "*"
semver = "1"
models = { path = "../models" }
